source "https://rubygems.org"

gem "github-pages", "~> 228", group: :jekyll_plugins
# If you have any plugins, put them here!
group :jekyll_plugins do
    gem "jekyll-minifier", "~> 0.1.10"
end

gem "webrick", "~> 1.8"