source "https://rubygems.org"

gem "jekyll", "~> 4.4"

# If you have any plugins, put them here!
group :jekyll_plugins do
    gem "jekyll-minifier", "~> 0.2.2"
end

gem "webrick", "~> 1.8"

# CI only: validates the built site in _site for broken internal links and
# malformed HTML. Not needed to build or serve the site locally.
group :test do
    gem "html-proofer", "~> 5.0"
end
